import type { FeedbackItem } from '@/types/domain';
import { daysAgo } from './projects';

export const mockFeedback: FeedbackItem[] = [
  {
    id: 'fb-1',
    title: 'Board freezes on large backlogs',
    description: 'When we have 400+ cards the board becomes unresponsive for 3-4 seconds on filter change.',
    source: 'zendesk',
    sourceRef: 'ZD-44821',
    submittedAt: `${daysAgo(12)}T09:30:00.000Z`,
    submittedBy: 'Acme Corp (Enterprise)',
    votes: 8,
    linkedWorkItemId: 'tk-5',
    status: 'linked',
    projectId: 'p-atlas',
    tags: ['performance', 'board'],
  },
  {
    id: 'fb-2',
    title: 'Need CSV export for sprint reports',
    description: 'Our PMO requires sprint velocity data in spreadsheet format for quarterly reviews.',
    source: 'intercom',
    sourceRef: 'IC-9912',
    submittedAt: `${daysAgo(20)}T14:15:00.000Z`,
    submittedBy: 'GlobalTech PM',
    votes: 5,
    status: 'reviewed',
    projectId: 'p-atlas',
    tags: ['export', 'reporting'],
  },
  {
    id: 'fb-3',
    title: 'Slack notifications are too noisy',
    description: 'Every status change fires a Slack message. We need granular notification rules.',
    source: 'slack',
    sourceRef: '#product-feedback/1684312',
    submittedAt: `${daysAgo(8)}T11:00:00.000Z`,
    votes: 12,
    status: 'reviewed',
    projectId: 'p-relay',
    tags: ['notifications', 'slack'],
  },
  {
    id: 'fb-4',
    title: 'Request: Jira import tool',
    description: 'We are migrating from Jira and need a way to bulk-import projects, epics, and stories.',
    source: 'email',
    sourceRef: 'support@meridian/thread/8891',
    submittedAt: `${daysAgo(30)}T08:00:00.000Z`,
    submittedBy: 'migration-team@bigcorp.com',
    votes: 15,
    status: 'reviewed',
    projectId: 'p-relay',
    tags: ['migration', 'import'],
  },
  {
    id: 'fb-5',
    title: 'Retention chart is confusing without a legend',
    description: 'The cohort grid colours have no legend. New users do not know what the shading means.',
    source: 'survey',
    sourceRef: 'NPS-Q3-2026-142',
    submittedAt: `${daysAgo(6)}T16:45:00.000Z`,
    votes: 3,
    status: 'new',
    projectId: 'p-orbit',
    tags: ['analytics', 'ux'],
  },
  {
    id: 'fb-6',
    title: 'Two-factor auth is a procurement blocker',
    description: 'Our security team will not approve the vendor without TOTP or WebAuthn support.',
    source: 'zendesk',
    sourceRef: 'ZD-45102',
    submittedAt: `${daysAgo(45)}T10:20:00.000Z`,
    submittedBy: 'SecureBank IT',
    votes: 22,
    linkedWorkItemId: 'tk-3',
    status: 'linked',
    projectId: 'p-forge',
    tags: ['security', 'enterprise'],
  },
  {
    id: 'fb-7',
    title: 'Onboarding checklist dismissed by accident',
    description: 'Clicked dismiss instead of minimise and now I cannot get the checklist back.',
    source: 'intercom',
    sourceRef: 'IC-10234',
    submittedAt: `${daysAgo(4)}T13:10:00.000Z`,
    submittedBy: 'New trial user',
    votes: 2,
    linkedWorkItemId: 'tk-10',
    status: 'linked',
    projectId: 'p-beacon',
    tags: ['onboarding', 'ux'],
  },
  {
    id: 'fb-8',
    title: 'Dark mode charts are unreadable',
    description: 'Chart lines blend into the dark background. Contrast is too low on the analytics page.',
    source: 'slack',
    sourceRef: '#design-feedback/1701442',
    submittedAt: `${daysAgo(9)}T15:30:00.000Z`,
    votes: 7,
    status: 'reviewed',
    projectId: 'p-orbit',
    tags: ['dark-mode', 'accessibility'],
  },
  {
    id: 'fb-9',
    title: 'Want to reorder checklist items',
    description: 'Task checklists do not support drag reordering. We have to delete and re-add items.',
    source: 'internal',
    submittedAt: `${daysAgo(18)}T10:00:00.000Z`,
    submittedBy: 'u-4',
    votes: 6,
    status: 'new',
    projectId: 'p-atlas',
    tags: ['checklists', 'ux'],
  },
  {
    id: 'fb-10',
    title: 'Webhook retries should use exponential backoff',
    description: 'Current retry is linear (30s fixed). Standard practice is exponential with jitter.',
    source: 'email',
    sourceRef: 'support@meridian/thread/9102',
    submittedAt: `${daysAgo(15)}T09:45:00.000Z`,
    submittedBy: 'dev@partnercorp.io',
    votes: 4,
    status: 'linked',
    linkedWorkItemId: 'tk-12',
    projectId: 'p-relay',
    tags: ['webhooks', 'reliability'],
  },
  {
    id: 'fb-11',
    title: 'Funnel step names truncate on mobile',
    description: 'On a phone screen the funnel step labels are cut off after ~10 characters.',
    source: 'survey',
    sourceRef: 'NPS-Q3-2026-187',
    submittedAt: `${daysAgo(5)}T12:00:00.000Z`,
    votes: 2,
    status: 'new',
    projectId: 'p-orbit',
    tags: ['mobile', 'analytics'],
  },
  {
    id: 'fb-12',
    title: 'Need SSO with Okta',
    description: 'Our org uses Okta for all SaaS apps. SAML SSO is a hard requirement.',
    source: 'zendesk',
    sourceRef: 'ZD-45501',
    submittedAt: `${daysAgo(52)}T11:30:00.000Z`,
    submittedBy: 'MedCorp IT Admin',
    votes: 18,
    status: 'reviewed',
    projectId: 'p-forge',
    tags: ['sso', 'enterprise'],
  },
  {
    id: 'fb-13',
    title: 'Calendar view should show sprint boundaries',
    description: 'Hard to see which tasks fall in which sprint when looking at the calendar.',
    source: 'internal',
    submittedAt: `${daysAgo(11)}T14:20:00.000Z`,
    submittedBy: 'u-8',
    votes: 9,
    status: 'new',
    projectId: 'p-atlas',
    tags: ['calendar', 'sprints'],
  },
  {
    id: 'fb-14',
    title: 'API rate limit too low for CI pipelines',
    description: 'Our CI creates 50 tasks per build. The 60/min rate limit causes failures.',
    source: 'email',
    sourceRef: 'support@meridian/thread/9344',
    submittedAt: `${daysAgo(22)}T08:30:00.000Z`,
    submittedBy: 'platform-eng@scaleup.dev',
    votes: 6,
    status: 'reviewed',
    projectId: 'p-relay',
    tags: ['api', 'rate-limiting'],
  },
  {
    id: 'fb-15',
    title: 'Digest email arrives at 3am in our timezone',
    description: 'The scheduled digest is sent at a fixed UTC time. We need timezone-aware scheduling.',
    source: 'intercom',
    sourceRef: 'IC-10501',
    submittedAt: `${daysAgo(7)}T10:15:00.000Z`,
    submittedBy: 'APAC team lead',
    votes: 4,
    status: 'new',
    projectId: 'p-orbit',
    tags: ['email', 'timezone'],
  },
  {
    id: 'fb-16',
    title: 'Design token colours do not match Figma',
    description: 'The grey-200 token in code is #E5E5E5 but in Figma it is #E8E8E8. Causes drift.',
    source: 'internal',
    submittedAt: `${daysAgo(3)}T09:00:00.000Z`,
    submittedBy: 'u-11',
    votes: 3,
    status: 'new',
    projectId: 'p-canvas',
    tags: ['design-system', 'tokens'],
  },
  {
    id: 'fb-17',
    title: 'Cannot assign a task to multiple people',
    description: 'Some tasks (e.g. pair programming) need two assignees. Currently only one is supported.',
    source: 'survey',
    sourceRef: 'NPS-Q3-2026-211',
    submittedAt: `${daysAgo(25)}T13:00:00.000Z`,
    votes: 14,
    status: 'dismissed',
    projectId: 'p-atlas',
    tags: ['assignments', 'collaboration'],
  },
  {
    id: 'fb-18',
    title: 'Approval flow needs an explicit reject action',
    description: 'Currently approvers can only approve or leave a comment. A reject button is needed.',
    source: 'zendesk',
    sourceRef: 'ZD-46001',
    submittedAt: `${daysAgo(16)}T11:45:00.000Z`,
    submittedBy: 'FinServ QA Lead',
    votes: 7,
    status: 'new',
    projectId: 'p-pulse',
    tags: ['approvals', 'workflow'],
  },
  {
    id: 'fb-19',
    title: 'Keyboard shortcut for quick-create is not discoverable',
    description: 'Took me two weeks to find Cmd+K. No hint in the UI.',
    source: 'slack',
    sourceRef: '#product-feedback/1723001',
    submittedAt: `${daysAgo(2)}T16:30:00.000Z`,
    votes: 5,
    status: 'new',
    projectId: 'p-atlas',
    tags: ['keyboard', 'discoverability'],
  },
  {
    id: 'fb-20',
    title: 'Release notes should auto-pull from task titles',
    description: 'We manually copy task titles into release notes. Should be generated from the linked tasks.',
    source: 'internal',
    submittedAt: `${daysAgo(13)}T15:00:00.000Z`,
    submittedBy: 'u-2',
    votes: 10,
    status: 'reviewed',
    projectId: 'p-atlas',
    tags: ['releases', 'automation'],
  },
  {
    id: 'fb-21',
    title: 'Support for custom task types',
    description: 'We use "RFC" and "ADR" as task types that do not map to story/bug/task.',
    source: 'email',
    sourceRef: 'support@meridian/thread/9501',
    submittedAt: `${daysAgo(40)}T09:20:00.000Z`,
    submittedBy: 'arch-team@enterprise.co',
    votes: 11,
    status: 'dismissed',
    projectId: 'p-atlas',
    tags: ['customisation', 'task-types'],
  },
  {
    id: 'fb-22',
    title: 'Burndown chart does not account for scope changes',
    description: 'When we add stories mid-sprint the ideal line does not update, making the chart misleading.',
    source: 'intercom',
    sourceRef: 'IC-10888',
    submittedAt: `${daysAgo(19)}T14:00:00.000Z`,
    submittedBy: 'Scrum Master at TechFlow',
    votes: 8,
    status: 'reviewed',
    projectId: 'p-orbit',
    tags: ['sprints', 'charts'],
  },
  {
    id: 'fb-23',
    title: 'Need audit trail for permission changes',
    description: 'When someone changes a role assignment we need to see who did it and when.',
    source: 'zendesk',
    sourceRef: 'ZD-46234',
    submittedAt: `${daysAgo(33)}T10:30:00.000Z`,
    submittedBy: 'ComplianceCo Admin',
    votes: 13,
    status: 'linked',
    linkedWorkItemId: 'tk-6',
    projectId: 'p-forge',
    tags: ['audit', 'compliance'],
  },
  {
    id: 'fb-24',
    title: 'Mobile app crashes when offline',
    description: 'Opening Pulse without network results in a white screen crash. No offline state.',
    source: 'survey',
    sourceRef: 'NPS-Q3-2026-299',
    submittedAt: `${daysAgo(28)}T12:00:00.000Z`,
    votes: 6,
    status: 'linked',
    linkedWorkItemId: 'tk-15',
    projectId: 'p-pulse',
    tags: ['mobile', 'offline'],
  },
  {
    id: 'fb-25',
    title: 'Roadmap items have no progress indicator',
    description: 'The roadmap Gantt bars are all one colour. Would be useful to shade by completion %.',
    source: 'slack',
    sourceRef: '#product-feedback/1730112',
    submittedAt: `${daysAgo(17)}T11:15:00.000Z`,
    votes: 9,
    status: 'new',
    projectId: 'p-atlas',
    tags: ['roadmap', 'ux'],
  },
  {
    id: 'fb-26',
    title: 'Cannot filter tasks by custom field values',
    description: 'The filter bar supports status, priority, assignee but not custom fields.',
    source: 'intercom',
    sourceRef: 'IC-11002',
    submittedAt: `${daysAgo(10)}T09:40:00.000Z`,
    submittedBy: 'Power user at DataDriven Inc',
    votes: 11,
    status: 'new',
    projectId: 'p-atlas',
    tags: ['filters', 'custom-fields'],
  },
  {
    id: 'fb-27',
    title: 'Webhook payload missing task labels',
    description: 'The task.updated webhook payload includes priority and status but not the labels array.',
    source: 'email',
    sourceRef: 'support@meridian/thread/9678',
    submittedAt: `${daysAgo(8)}T14:30:00.000Z`,
    submittedBy: 'integrations@startupx.io',
    votes: 3,
    status: 'new',
    projectId: 'p-relay',
    tags: ['webhooks', 'api'],
  },
  {
    id: 'fb-28',
    title: 'Onboarding tour blocks interaction',
    description: 'The tour overlay prevents clicking anything until all steps are completed. Feels forced.',
    source: 'survey',
    sourceRef: 'NPS-Q3-2026-315',
    submittedAt: `${daysAgo(3)}T10:50:00.000Z`,
    votes: 4,
    status: 'new',
    projectId: 'p-beacon',
    tags: ['onboarding', 'ux'],
  },
  {
    id: 'fb-29',
    title: 'Need SCIM provisioning for user management',
    description: 'We manage 200+ users. Manual invite is not scalable. SCIM is the standard.',
    source: 'zendesk',
    sourceRef: 'ZD-46502',
    submittedAt: `${daysAgo(55)}T08:15:00.000Z`,
    submittedBy: 'MegaCorp IT Ops',
    votes: 16,
    status: 'reviewed',
    projectId: 'p-forge',
    tags: ['provisioning', 'enterprise'],
  },
  {
    id: 'fb-30',
    title: 'Component storybook is out of date',
    description: 'Several Canvas v2 stories are broken since the token migration started.',
    source: 'internal',
    submittedAt: `${daysAgo(1)}T11:00:00.000Z`,
    submittedBy: 'u-5',
    votes: 2,
    status: 'new',
    projectId: 'p-canvas',
    tags: ['design-system', 'docs'],
  },
];
