import type { ISODate } from '@/types/domain';
import { daysAgo } from './projects';

export interface MockIdea {
  id: string;
  title: string;
  description: string;
  stage: 'new' | 'under_review' | 'accepted' | 'rejected' | 'merged';
  categoryId?: string;
  projectId: string;
  submittedBy: string;
  votes: number;
  createdAt: ISODate;
  updatedAt: ISODate;
  timeInCurrentStage: number; // days
  tags: string[];
  mergedInto?: string;
}

export const mockIdeas: MockIdea[] = [
  {
    id: 'idea-1',
    title: 'Bulk status update from the board view',
    description: 'Allow multi-select on board cards and change status in one action.',
    stage: 'accepted',
    categoryId: 'cat-ux',
    projectId: 'p-atlas',
    submittedBy: 'u-4',
    votes: 34,
    createdAt: `${daysAgo(42)}T09:15:00.000Z`,
    updatedAt: `${daysAgo(8)}T14:30:00.000Z`,
    timeInCurrentStage: 8,
    tags: ['productivity', 'board'],
  },
  {
    id: 'idea-2',
    title: 'Custom swimlanes on the Kanban board',
    description: 'Group columns by assignee, priority, or a custom field instead of just status.',
    stage: 'under_review',
    categoryId: 'cat-ux',
    projectId: 'p-atlas',
    submittedBy: 'u-14',
    votes: 27,
    createdAt: `${daysAgo(35)}T11:00:00.000Z`,
    updatedAt: `${daysAgo(3)}T10:20:00.000Z`,
    timeInCurrentStage: 12,
    tags: ['board', 'customisation'],
  },
  {
    id: 'idea-3',
    title: 'Time-tracking integration with Toggl',
    description: 'Sync logged hours from Toggl into task estimates automatically.',
    stage: 'new',
    projectId: 'p-relay',
    submittedBy: 'u-8',
    votes: 19,
    createdAt: `${daysAgo(14)}T08:45:00.000Z`,
    updatedAt: `${daysAgo(14)}T08:45:00.000Z`,
    timeInCurrentStage: 14,
    tags: ['integration', 'time-tracking'],
  },
  {
    id: 'idea-4',
    title: 'Dark mode for the analytics dashboards',
    description: 'Charts and retention grids should respect the system/app dark-mode setting.',
    stage: 'accepted',
    categoryId: 'cat-design',
    projectId: 'p-orbit',
    submittedBy: 'u-11',
    votes: 41,
    createdAt: `${daysAgo(60)}T13:00:00.000Z`,
    updatedAt: `${daysAgo(15)}T09:10:00.000Z`,
    timeInCurrentStage: 15,
    tags: ['design', 'dark-mode'],
  },
  {
    id: 'idea-5',
    title: 'Slack thread auto-link when a task is mentioned',
    description: 'If someone mentions a task key in Slack, auto-create an integration ref.',
    stage: 'under_review',
    categoryId: 'cat-integration',
    projectId: 'p-relay',
    submittedBy: 'u-3',
    votes: 22,
    createdAt: `${daysAgo(28)}T16:30:00.000Z`,
    updatedAt: `${daysAgo(5)}T11:00:00.000Z`,
    timeInCurrentStage: 5,
    tags: ['slack', 'automation'],
  },
  {
    id: 'idea-6',
    title: 'Dependency graph visualisation',
    description: 'Show a DAG of task dependencies so blocked chains are visible at a glance.',
    stage: 'accepted',
    categoryId: 'cat-ux',
    projectId: 'p-atlas',
    submittedBy: 'u-2',
    votes: 38,
    createdAt: `${daysAgo(55)}T10:00:00.000Z`,
    updatedAt: `${daysAgo(10)}T15:45:00.000Z`,
    timeInCurrentStage: 10,
    tags: ['dependencies', 'visualisation'],
  },
  {
    id: 'idea-7',
    title: 'AI-generated sprint summaries',
    description: 'At sprint close, generate a natural-language summary of what shipped and what carried over.',
    stage: 'new',
    projectId: 'p-atlas',
    submittedBy: 'u-1',
    votes: 45,
    createdAt: `${daysAgo(7)}T14:20:00.000Z`,
    updatedAt: `${daysAgo(7)}T14:20:00.000Z`,
    timeInCurrentStage: 7,
    tags: ['ai', 'sprints'],
  },
  {
    id: 'idea-8',
    title: 'Guest access for external stakeholders',
    description: 'Let clients view a filtered project board without a full seat.',
    stage: 'under_review',
    categoryId: 'cat-access',
    projectId: 'p-forge',
    submittedBy: 'u-8',
    votes: 31,
    createdAt: `${daysAgo(48)}T09:30:00.000Z`,
    updatedAt: `${daysAgo(6)}T13:15:00.000Z`,
    timeInCurrentStage: 18,
    tags: ['access', 'external'],
  },
  {
    id: 'idea-9',
    title: 'Recurring task templates',
    description: 'Define a template that auto-creates tasks on a schedule (weekly retro prep, monthly reports).',
    stage: 'accepted',
    categoryId: 'cat-productivity',
    projectId: 'p-atlas',
    submittedBy: 'u-3',
    votes: 29,
    createdAt: `${daysAgo(70)}T11:45:00.000Z`,
    updatedAt: `${daysAgo(20)}T10:00:00.000Z`,
    timeInCurrentStage: 20,
    tags: ['automation', 'templates'],
  },
  {
    id: 'idea-10',
    title: 'Export roadmap to PDF or PNG',
    description: 'One-click export of the Gantt-style roadmap for stakeholder decks.',
    stage: 'rejected',
    categoryId: 'cat-reporting',
    projectId: 'p-atlas',
    submittedBy: 'u-13',
    votes: 12,
    createdAt: `${daysAgo(90)}T15:00:00.000Z`,
    updatedAt: `${daysAgo(45)}T09:30:00.000Z`,
    timeInCurrentStage: 45,
    tags: ['export', 'roadmap'],
  },
  {
    id: 'idea-11',
    title: 'Webhook event for sprint start/end',
    description: 'Fire a webhook when a sprint is started or completed so CI pipelines can react.',
    stage: 'accepted',
    categoryId: 'cat-integration',
    projectId: 'p-relay',
    submittedBy: 'u-6',
    votes: 16,
    createdAt: `${daysAgo(32)}T10:10:00.000Z`,
    updatedAt: `${daysAgo(12)}T14:00:00.000Z`,
    timeInCurrentStage: 12,
    tags: ['webhooks', 'ci-cd'],
  },
  {
    id: 'idea-12',
    title: 'Capacity heatmap per team',
    description: 'Visual heatmap showing which weeks are over- or under-allocated across teams.',
    stage: 'new',
    projectId: 'p-orbit',
    submittedBy: 'u-9',
    votes: 23,
    createdAt: `${daysAgo(10)}T09:00:00.000Z`,
    updatedAt: `${daysAgo(10)}T09:00:00.000Z`,
    timeInCurrentStage: 10,
    tags: ['capacity', 'analytics'],
  },
  {
    id: 'idea-13',
    title: 'Custom onboarding checklist per role',
    description: 'Let admins define different checklists for devs, designers, and PMs during onboarding.',
    stage: 'merged',
    categoryId: 'cat-onboarding',
    projectId: 'p-beacon',
    submittedBy: 'u-5',
    votes: 33,
    createdAt: `${daysAgo(80)}T14:00:00.000Z`,
    updatedAt: `${daysAgo(30)}T16:00:00.000Z`,
    timeInCurrentStage: 30,
    tags: ['onboarding', 'roles'],
    mergedInto: 'tk-8',
  },
  {
    id: 'idea-14',
    title: 'Personal dashboard widgets',
    description: 'Let each user arrange their own dashboard with drag-and-drop widgets.',
    stage: 'under_review',
    categoryId: 'cat-ux',
    projectId: 'p-atlas',
    submittedBy: 'u-14',
    votes: 26,
    createdAt: `${daysAgo(22)}T11:30:00.000Z`,
    updatedAt: `${daysAgo(4)}T10:45:00.000Z`,
    timeInCurrentStage: 4,
    tags: ['dashboard', 'personalisation'],
  },
  {
    id: 'idea-15',
    title: 'Two-factor authentication',
    description: 'Add TOTP-based 2FA to the login flow for enterprise accounts.',
    stage: 'accepted',
    categoryId: 'cat-security',
    projectId: 'p-forge',
    submittedBy: 'u-7',
    votes: 52,
    createdAt: `${daysAgo(100)}T08:00:00.000Z`,
    updatedAt: `${daysAgo(25)}T11:30:00.000Z`,
    timeInCurrentStage: 25,
    tags: ['security', 'enterprise'],
  },
  {
    id: 'idea-16',
    title: 'Inline commenting on task descriptions',
    description: 'Select text in a description and leave a comment anchored to that passage.',
    stage: 'new',
    projectId: 'p-atlas',
    submittedBy: 'u-4',
    votes: 18,
    createdAt: `${daysAgo(5)}T13:00:00.000Z`,
    updatedAt: `${daysAgo(5)}T13:00:00.000Z`,
    timeInCurrentStage: 5,
    tags: ['collaboration', 'comments'],
  },
  {
    id: 'idea-17',
    title: 'Mobile push notifications for blocked tasks',
    description: 'Get a push notification on Pulse when a task you own becomes blocked.',
    stage: 'rejected',
    projectId: 'p-pulse',
    submittedBy: 'u-12',
    votes: 8,
    createdAt: `${daysAgo(50)}T10:30:00.000Z`,
    updatedAt: `${daysAgo(38)}T09:00:00.000Z`,
    timeInCurrentStage: 38,
    tags: ['mobile', 'notifications'],
  },
  {
    id: 'idea-18',
    title: 'Audit log export for compliance',
    description: 'Export the audit trail as CSV for SOC 2 evidence collection.',
    stage: 'under_review',
    categoryId: 'cat-compliance',
    projectId: 'p-forge',
    submittedBy: 'u-8',
    votes: 20,
    createdAt: `${daysAgo(38)}T15:45:00.000Z`,
    updatedAt: `${daysAgo(2)}T14:00:00.000Z`,
    timeInCurrentStage: 9,
    tags: ['compliance', 'audit'],
  },
  {
    id: 'idea-19',
    title: 'Design token playground in Canvas docs',
    description: 'Interactive page in the design system docs where designers can preview token combos.',
    stage: 'new',
    categoryId: 'cat-design',
    projectId: 'p-canvas',
    submittedBy: 'u-11',
    votes: 15,
    createdAt: `${daysAgo(6)}T10:00:00.000Z`,
    updatedAt: `${daysAgo(6)}T10:00:00.000Z`,
    timeInCurrentStage: 6,
    tags: ['design-system', 'docs'],
  },
  {
    id: 'idea-20',
    title: 'Natural-language search across all work items',
    description: 'Type a question like "what blocked Atlas last week?" and get relevant results.',
    stage: 'new',
    projectId: 'p-atlas',
    submittedBy: 'u-1',
    votes: 57,
    createdAt: `${daysAgo(3)}T16:00:00.000Z`,
    updatedAt: `${daysAgo(3)}T16:00:00.000Z`,
    timeInCurrentStage: 3,
    tags: ['ai', 'search'],
  },
];
