import type { Milestone, Release, RoadmapItem, Sprint } from '@/types/domain';
import { daysAgo, daysFromToday } from './projects';

export const sprints: Sprint[] = [
  {
    id: 's-atl-12',
    name: 'ATL Sprint 12',
    goal: 'Ship the collapsible shell and saved views behind the beta flag.',
    projectId: 'p-atlas',
    teamId: 't-core',
    startDate: daysAgo(44),
    endDate: daysAgo(31),
    status: 'completed',
    capacityPoints: 48,
    committedPoints: 46,
    completedPoints: 41,
  },
  {
    id: 's-atl-13',
    name: 'ATL Sprint 13',
    goal: 'Unified task surface with keyboard-first navigation.',
    projectId: 'p-atlas',
    teamId: 't-core',
    startDate: daysAgo(30),
    endDate: daysAgo(17),
    status: 'completed',
    capacityPoints: 48,
    committedPoints: 50,
    completedPoints: 44,
  },
  {
    id: 's-atl-14',
    name: 'ATL Sprint 14',
    goal: 'Board and list parity, plus the task detail drawer on tablet.',
    projectId: 'p-atlas',
    teamId: 't-core',
    startDate: daysAgo(16),
    endDate: daysAgo(3),
    status: 'completed',
    capacityPoints: 46,
    committedPoints: 44,
    completedPoints: 45,
  },
  {
    id: 's-atl-15',
    name: 'ATL Sprint 15',
    goal: 'Close out accessibility findings and harden the saved-view API contract.',
    projectId: 'p-atlas',
    teamId: 't-core',
    startDate: daysAgo(2),
    endDate: daysFromToday(11),
    status: 'active',
    capacityPoints: 46,
    committedPoints: 42,
    completedPoints: 13,
  },
  {
    id: 's-atl-16',
    name: 'ATL Sprint 16',
    goal: 'Tablet polish and launch-readiness checklist.',
    projectId: 'p-atlas',
    teamId: 't-core',
    startDate: daysFromToday(12),
    endDate: daysFromToday(25),
    status: 'planned',
    capacityPoints: 46,
    committedPoints: 18,
    completedPoints: 0,
  },
  {
    id: 's-orb-6',
    name: 'ORB Sprint 6',
    goal: 'Funnel exploration MVP against the rollup tables.',
    projectId: 'p-orbit',
    teamId: 't-growth',
    startDate: daysAgo(15),
    endDate: daysAgo(2),
    status: 'completed',
    capacityPoints: 38,
    committedPoints: 40,
    completedPoints: 29,
  },
  {
    id: 's-orb-7',
    name: 'ORB Sprint 7',
    goal: 'Cohort retention view and scheduled digest delivery.',
    projectId: 'p-orbit',
    teamId: 't-growth',
    startDate: daysAgo(1),
    endDate: daysFromToday(12),
    status: 'active',
    capacityPoints: 38,
    committedPoints: 36,
    completedPoints: 8,
  },
  {
    id: 's-frg-21',
    name: 'FRG Sprint 21',
    goal: 'Dual-write permissions shadow comparison running clean for 7 days.',
    projectId: 'p-forge',
    teamId: 't-platform',
    startDate: daysAgo(5),
    endDate: daysFromToday(8),
    status: 'active',
    capacityPoints: 42,
    committedPoints: 45,
    completedPoints: 11,
  },
  {
    id: 's-bcn-3',
    name: 'BCN Sprint 3',
    goal: 'Role-aware checklist engine wired to activation events.',
    projectId: 'p-beacon',
    teamId: 't-growth',
    startDate: daysAgo(4),
    endDate: daysFromToday(9),
    status: 'active',
    capacityPoints: 32,
    committedPoints: 28,
    completedPoints: 7,
  },
  {
    id: 's-bcn-4',
    name: 'BCN Sprint 4',
    goal: 'In-product tour authoring and analytics instrumentation.',
    projectId: 'p-beacon',
    teamId: 't-growth',
    startDate: daysFromToday(10),
    endDate: daysFromToday(23),
    status: 'planned',
    capacityPoints: 32,
    committedPoints: 0,
    completedPoints: 0,
  },
];

export const releases: Release[] = [
  {
    id: 'rel-atlas-1',
    version: '3.4.0',
    name: 'Atlas Beta',
    description: 'First external beta of the rebuilt workspace shell for design-partner accounts.',
    projectId: 'p-atlas',
    ownerId: 'u-1',
    targetDate: daysFromToday(38),
    status: 'in_development',
    deploymentStatus: 'staging',
    progress: 62,
    notes:
      'Collapsible navigation, saved views, unified task surface and the new task detail drawer. Mobile board remains read-only in this build.',
    readiness: [
      { id: 'rc-1', label: 'Accessibility audit signed off', done: false, ownerId: 'u-7' },
      { id: 'rc-2', label: 'Performance budget verified (LCP < 2.0s)', done: true, ownerId: 'u-4' },
      { id: 'rc-3', label: 'Design QA pass complete', done: true, ownerId: 'u-5' },
      { id: 'rc-4', label: 'Regression suite green on staging', done: false, ownerId: 'u-12' },
      { id: 'rc-5', label: 'Release notes drafted', done: false, ownerId: 'u-8' },
      { id: 'rc-6', label: 'Rollback plan reviewed', done: true, ownerId: 'u-2' },
    ],
  },
  {
    id: 'rel-orbit-1',
    version: '1.0.0',
    name: 'Orbit GA',
    description: 'General availability of the analytics suite with funnels, retention and digests.',
    projectId: 'p-orbit',
    ownerId: 'u-3',
    targetDate: daysFromToday(21),
    status: 'in_testing',
    deploymentStatus: 'canary',
    progress: 48,
    notes:
      'Funnel exploration and cohort retention are feature-complete. Scheduled digests are behind a flag pending latency work.',
    readiness: [
      { id: 'rc-7', label: 'p95 query latency within SLA', done: false, ownerId: 'u-9' },
      { id: 'rc-8', label: 'Data accuracy reconciliation complete', done: true, ownerId: 'u-9' },
      { id: 'rc-9', label: 'Load test at 3x peak', done: false, ownerId: 'u-6' },
      { id: 'rc-10', label: 'Docs and in-app help published', done: false, ownerId: 'u-3' },
      { id: 'rc-11', label: 'Pricing and packaging confirmed', done: true, ownerId: 'u-1' },
    ],
  },
  {
    id: 'rel-forge-2',
    version: '2.8.0',
    name: 'Forge Multi-Region',
    description: 'Active-active multi-region failover and the rewritten permissions service.',
    projectId: 'p-forge',
    ownerId: 'u-8',
    targetDate: daysFromToday(9),
    status: 'in_testing',
    deploymentStatus: 'staging',
    progress: 71,
    notes:
      'Failover drills pass in two of three regions. Permissions dual-write is live; read cutover is the remaining gate.',
    readiness: [
      { id: 'rc-12', label: 'Failover drill passed in all regions', done: false, ownerId: 'u-10' },
      { id: 'rc-13', label: 'Permissions shadow diff clean for 7 days', done: false, ownerId: 'u-6' },
      { id: 'rc-14', label: 'Tenant isolation penetration test', done: true, ownerId: 'u-7' },
      { id: 'rc-15', label: 'Runbooks updated', done: true, ownerId: 'u-10' },
      { id: 'rc-16', label: 'Customer comms scheduled', done: false, ownerId: 'u-8' },
    ],
  },
  {
    id: 'rel-beacon-1',
    version: '0.9.0',
    name: 'Beacon Pilot',
    description: 'Pilot release of guided onboarding to ten volunteer accounts.',
    projectId: 'p-beacon',
    ownerId: 'u-3',
    targetDate: daysFromToday(54),
    status: 'planned',
    deploymentStatus: 'not_started',
    progress: 20,
    notes: 'Checklist engine and activation milestones only. Tours and localisation follow in 1.0.',
    readiness: [
      { id: 'rc-17', label: 'Pilot cohort selected', done: true, ownerId: 'u-3' },
      { id: 'rc-18', label: 'Activation events instrumented', done: false, ownerId: 'u-9' },
      { id: 'rc-19', label: 'Support playbook written', done: false, ownerId: 'u-13' },
    ],
  },
  {
    id: 'rel-atlas-0',
    version: '3.3.2',
    name: 'Atlas Foundations',
    description: 'Internal foundations release: routing, theming and the token pipeline.',
    projectId: 'p-atlas',
    ownerId: 'u-2',
    targetDate: daysAgo(24),
    releasedOn: daysAgo(23),
    status: 'released',
    deploymentStatus: 'production',
    progress: 100,
    notes: 'Shipped without incident. Two follow-up polish items moved to 3.4.0.',
    readiness: [
      { id: 'rc-20', label: 'Regression suite green', done: true, ownerId: 'u-12' },
      { id: 'rc-21', label: 'Rollback plan reviewed', done: true, ownerId: 'u-2' },
      { id: 'rc-22', label: 'Release notes published', done: true, ownerId: 'u-8' },
    ],
  },
  {
    id: 'rel-pulse-1',
    version: '1.2.0',
    name: 'Pulse Mobile',
    description: 'Approvals, standup updates and notification triage on mobile.',
    projectId: 'p-pulse',
    ownerId: 'u-3',
    targetDate: daysAgo(31),
    releasedOn: daysAgo(30),
    status: 'released',
    deploymentStatus: 'production',
    progress: 100,
    notes: 'Adoption at 38% of weekly active users four weeks post-launch.',
    readiness: [
      { id: 'rc-23', label: 'Store review approved', done: true, ownerId: 'u-14' },
      { id: 'rc-24', label: 'Crash-free rate above 99.5%', done: true, ownerId: 'u-12' },
      { id: 'rc-25', label: 'Release notes published', done: true, ownerId: 'u-3' },
    ],
  },
  {
    id: 'rel-relay-1',
    version: '0.4.0',
    name: 'Relay Preview',
    description: 'Webhook delivery and the first three connectors, paused pending platform work.',
    projectId: 'p-relay',
    ownerId: 'u-1',
    targetDate: daysFromToday(120),
    status: 'planned',
    deploymentStatus: 'not_started',
    progress: 26,
    notes: 'On hold until Forge multi-region ships; connector contracts are drafted.',
    readiness: [{ id: 'rc-26', label: 'Connector contracts reviewed', done: true, ownerId: 'u-6' }],
  },
];

export const milestones: Milestone[] = [
  {
    id: 'm-1',
    name: 'Atlas design partner review',
    description: 'Walkthrough with the five design-partner accounts and consolidated feedback log.',
    date: daysFromToday(6),
    projectId: 'p-atlas',
    releaseId: 'rel-atlas-1',
    completed: false,
  },
  {
    id: 'm-2',
    name: 'Atlas code freeze',
    description: 'No further feature merges into the 3.4.0 branch.',
    date: daysFromToday(30),
    projectId: 'p-atlas',
    releaseId: 'rel-atlas-1',
    completed: false,
  },
  {
    id: 'm-3',
    name: 'Orbit data accuracy sign-off',
    description: 'Reconciliation of funnel and retention numbers against the warehouse of record.',
    date: daysAgo(3),
    projectId: 'p-orbit',
    releaseId: 'rel-orbit-1',
    completed: true,
  },
  {
    id: 'm-4',
    name: 'Orbit load test at 3x peak',
    description: 'Sustained synthetic load across the three largest tenant shapes.',
    date: daysFromToday(10),
    projectId: 'p-orbit',
    releaseId: 'rel-orbit-1',
    completed: false,
  },
  {
    id: 'm-5',
    name: 'Forge region three failover drill',
    description: 'Final drill covering the APAC region with full traffic shift.',
    date: daysFromToday(4),
    projectId: 'p-forge',
    releaseId: 'rel-forge-2',
    completed: false,
  },
  {
    id: 'm-6',
    name: 'Forge permissions read cutover',
    description: 'Flip reads to the new permissions service after a clean shadow window.',
    date: daysFromToday(7),
    projectId: 'p-forge',
    releaseId: 'rel-forge-2',
    completed: false,
  },
  {
    id: 'm-7',
    name: 'Beacon pilot kickoff',
    description: 'Enable guided onboarding for the ten pilot accounts.',
    date: daysFromToday(47),
    projectId: 'p-beacon',
    releaseId: 'rel-beacon-1',
    completed: false,
  },
  {
    id: 'm-8',
    name: 'Canvas v3 token freeze',
    description: 'Lock the token contract so downstream teams can migrate safely.',
    date: daysFromToday(34),
    projectId: 'p-canvas',
    completed: false,
  },
  {
    id: 'm-9',
    name: 'Pulse post-launch review',
    description: 'Adoption, crash rate and support volume retrospective.',
    date: daysAgo(9),
    projectId: 'p-pulse',
    releaseId: 'rel-pulse-1',
    completed: true,
  },
];

export const roadmapItems: RoadmapItem[] = [
  {
    id: 'rm-1',
    title: 'Unified workspace experience',
    description: 'Umbrella initiative covering the shell rebuild, saved views and cross-surface parity.',
    kind: 'initiative',
    projectId: 'p-atlas',
    productArea: 'Core Experience',
    teamId: 't-core',
    ownerId: 'u-1',
    startDate: daysAgo(96),
    endDate: daysFromToday(62),
    progress: 62,
    priority: 'critical',
    health: 'on_track',
    dependsOnIds: [],
  },
  {
    id: 'rm-2',
    title: 'Navigation shell and saved views',
    description: 'Collapsible sidebar, workspace switching and per-user saved view persistence.',
    kind: 'epic',
    projectId: 'p-atlas',
    productArea: 'Core Experience',
    teamId: 't-core',
    ownerId: 'u-2',
    startDate: daysAgo(96),
    endDate: daysAgo(12),
    progress: 94,
    priority: 'high',
    health: 'on_track',
    dependsOnIds: ['rm-1'],
  },
  {
    id: 'rm-3',
    title: 'Unified task surface',
    description: 'Board, list and calendar views sharing one task model and one filter contract.',
    kind: 'epic',
    projectId: 'p-atlas',
    productArea: 'Core Experience',
    teamId: 't-core',
    ownerId: 'u-4',
    startDate: daysAgo(34),
    endDate: daysFromToday(28),
    progress: 58,
    priority: 'critical',
    health: 'at_risk',
    dependsOnIds: ['rm-2'],
  },
  {
    id: 'rm-4',
    title: 'Accessibility conformance to WCAG 2.2 AA',
    description: 'Keyboard parity for drag-and-drop, focus management in drawers, contrast audit.',
    kind: 'feature',
    projectId: 'p-atlas',
    productArea: 'Core Experience',
    teamId: 't-core',
    ownerId: 'u-4',
    startDate: daysAgo(10),
    endDate: daysFromToday(26),
    progress: 35,
    priority: 'high',
    health: 'at_risk',
    dependsOnIds: ['rm-3'],
  },
  {
    id: 'rm-5',
    title: 'Atlas Beta',
    description: 'Design-partner beta of the rebuilt workspace.',
    kind: 'release',
    projectId: 'p-atlas',
    productArea: 'Core Experience',
    teamId: 't-core',
    ownerId: 'u-1',
    startDate: daysFromToday(36),
    endDate: daysFromToday(38),
    progress: 0,
    priority: 'critical',
    health: 'on_track',
    dependsOnIds: ['rm-3', 'rm-4'],
    releaseId: 'rel-atlas-1',
  },
  {
    id: 'rm-6',
    title: 'Self-serve product analytics',
    description: 'Initiative to give every product team first-party funnels, retention and digests.',
    kind: 'initiative',
    projectId: 'p-orbit',
    productArea: 'Analytics',
    teamId: 't-growth',
    ownerId: 'u-3',
    startDate: daysAgo(64),
    endDate: daysFromToday(80),
    progress: 44,
    priority: 'high',
    health: 'at_risk',
    dependsOnIds: [],
  },
  {
    id: 'rm-7',
    title: 'Metrics store and daily rollups',
    description: 'Columnar metrics store with pre-aggregated daily rollups behind a typed query layer.',
    kind: 'epic',
    projectId: 'p-orbit',
    productArea: 'Analytics',
    teamId: 't-platform',
    ownerId: 'u-6',
    startDate: daysAgo(64),
    endDate: daysFromToday(14),
    progress: 66,
    priority: 'critical',
    health: 'at_risk',
    dependsOnIds: ['rm-6'],
  },
  {
    id: 'rm-8',
    title: 'Funnel and retention exploration',
    description: 'Interactive funnel builder plus cohort retention grid with export.',
    kind: 'feature',
    projectId: 'p-orbit',
    productArea: 'Analytics',
    teamId: 't-growth',
    ownerId: 'u-9',
    startDate: daysAgo(30),
    endDate: daysFromToday(16),
    progress: 52,
    priority: 'high',
    health: 'on_track',
    dependsOnIds: ['rm-7'],
  },
  {
    id: 'rm-9',
    title: 'Orbit GA',
    description: 'General availability of the analytics suite.',
    kind: 'release',
    projectId: 'p-orbit',
    productArea: 'Analytics',
    teamId: 't-growth',
    ownerId: 'u-3',
    startDate: daysFromToday(19),
    endDate: daysFromToday(21),
    progress: 0,
    priority: 'high',
    health: 'at_risk',
    dependsOnIds: ['rm-7', 'rm-8'],
    releaseId: 'rel-orbit-1',
  },
  {
    id: 'rm-10',
    title: 'Enterprise readiness',
    description: 'Multi-region resilience, tenant isolation and auditable permissions.',
    kind: 'initiative',
    projectId: 'p-forge',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-8',
    startDate: daysAgo(132),
    endDate: daysFromToday(40),
    progress: 71,
    priority: 'critical',
    health: 'off_track',
    dependsOnIds: [],
  },
  {
    id: 'rm-11',
    title: 'Permissions service rewrite',
    description: 'Replace the inherited ACL table with a typed policy service and audit trail.',
    kind: 'epic',
    projectId: 'p-forge',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-6',
    startDate: daysAgo(74),
    endDate: daysFromToday(7),
    progress: 78,
    priority: 'critical',
    health: 'off_track',
    dependsOnIds: ['rm-10'],
  },
  {
    id: 'rm-12',
    title: 'Active-active multi-region',
    description: 'Region-level failover with verified drills and documented runbooks.',
    kind: 'epic',
    projectId: 'p-forge',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-10',
    startDate: daysAgo(110),
    endDate: daysFromToday(5),
    progress: 84,
    priority: 'critical',
    health: 'at_risk',
    dependsOnIds: ['rm-10'],
  },
  {
    id: 'rm-13',
    title: 'Region three failover drill',
    description: 'Final APAC drill with full traffic shift.',
    kind: 'milestone',
    projectId: 'p-forge',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-10',
    startDate: daysFromToday(4),
    endDate: daysFromToday(4),
    progress: 0,
    priority: 'critical',
    health: 'at_risk',
    dependsOnIds: ['rm-12'],
  },
  {
    id: 'rm-14',
    title: 'Forge Multi-Region',
    description: 'Multi-region and permissions release.',
    kind: 'release',
    projectId: 'p-forge',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-8',
    startDate: daysFromToday(8),
    endDate: daysFromToday(9),
    progress: 0,
    priority: 'critical',
    health: 'off_track',
    dependsOnIds: ['rm-11', 'rm-12'],
    releaseId: 'rel-forge-2',
  },
  {
    id: 'rm-15',
    title: 'Activation and time-to-value',
    description: 'Get a new workspace to its first meaningful outcome inside one session.',
    kind: 'initiative',
    projectId: 'p-beacon',
    productArea: 'Growth',
    teamId: 't-growth',
    ownerId: 'u-3',
    startDate: daysAgo(41),
    endDate: daysFromToday(110),
    progress: 33,
    priority: 'high',
    health: 'on_track',
    dependsOnIds: [],
  },
  {
    id: 'rm-16',
    title: 'Role-aware onboarding checklists',
    description: 'Checklist engine driven by activation events and the inviter-selected role.',
    kind: 'epic',
    projectId: 'p-beacon',
    productArea: 'Growth',
    teamId: 't-growth',
    ownerId: 'u-3',
    startDate: daysAgo(41),
    endDate: daysFromToday(30),
    progress: 46,
    priority: 'high',
    health: 'on_track',
    dependsOnIds: ['rm-15'],
  },
  {
    id: 'rm-17',
    title: 'In-product tours',
    description: 'Authorable, dismissible tours anchored to real UI targets.',
    kind: 'feature',
    projectId: 'p-beacon',
    productArea: 'Growth',
    teamId: 't-design',
    ownerId: 'u-5',
    startDate: daysFromToday(10),
    endDate: daysFromToday(52),
    progress: 0,
    priority: 'medium',
    health: 'on_track',
    dependsOnIds: ['rm-16'],
  },
  {
    id: 'rm-18',
    title: 'Canvas Design System v3',
    description: 'Token-driven components with dark-mode parity and documented a11y contracts.',
    kind: 'initiative',
    projectId: 'p-canvas',
    productArea: 'Design',
    teamId: 't-design',
    ownerId: 'u-5',
    startDate: daysFromToday(-8),
    endDate: daysFromToday(96),
    progress: 11,
    priority: 'medium',
    health: 'on_track',
    dependsOnIds: [],
  },
  {
    id: 'rm-19',
    title: 'Token pipeline and theming contract',
    description: 'Single token source feeding light and dark themes plus docs generation.',
    kind: 'epic',
    projectId: 'p-canvas',
    productArea: 'Design',
    teamId: 't-design',
    ownerId: 'u-11',
    startDate: daysFromToday(-8),
    endDate: daysFromToday(34),
    progress: 22,
    priority: 'medium',
    health: 'on_track',
    dependsOnIds: ['rm-18'],
  },
  {
    id: 'rm-20',
    title: 'Public API and webhooks',
    description: 'Outbound webhooks and a versioned REST surface for partner integrations.',
    kind: 'epic',
    projectId: 'p-relay',
    productArea: 'Platform',
    teamId: 't-platform',
    ownerId: 'u-6',
    startDate: daysFromToday(44),
    endDate: daysFromToday(120),
    progress: 26,
    priority: 'medium',
    health: 'at_risk',
    dependsOnIds: ['rm-11'],
  },
];
