import { addDays, formatISO, startOfDay, subDays } from 'date-fns';
import type { Label, CustomFieldDefinition, Project, Risk } from '@/types/domain';
import { chartPalette } from '@/app/tokens';
import { DEFAULT_WORKSPACE_ID } from './people';

/** All relative dates in the mock set are derived from this anchor so the
 *  fixtures always look current regardless of when the app is opened. */
export const TODAY = startOfDay(new Date());

export const iso = (date: Date): string => formatISO(date, { representation: 'date' });
export const isoAt = (date: Date): string => date.toISOString();
export const daysFromToday = (days: number): string => iso(addDays(TODAY, days));
export const daysAgo = (days: number): string => iso(subDays(TODAY, days));

export const labels: Label[] = [
  { id: 'l-1', name: 'accessibility', color: chartPalette[1]! },
  { id: 'l-2', name: 'performance', color: chartPalette[3]! },
  { id: 'l-3', name: 'tech-debt', color: chartPalette[5]! },
  { id: 'l-4', name: 'customer-request', color: chartPalette[0]! },
  { id: 'l-5', name: 'security', color: chartPalette[6]! },
  { id: 'l-6', name: 'design-system', color: chartPalette[2]! },
  { id: 'l-7', name: 'analytics', color: chartPalette[4]! },
  { id: 'l-8', name: 'mobile', color: chartPalette[7]! },
  { id: 'l-9', name: 'compliance', color: chartPalette[5]! },
  { id: 'l-10', name: 'onboarding', color: chartPalette[0]! },
];

export const customFieldDefinitions: CustomFieldDefinition[] = [
  {
    id: 'cf-impact',
    name: 'Customer Impact',
    kind: 'select',
    options: ['Blocker', 'Major', 'Moderate', 'Minor'],
    appliesTo: ['bug', 'story', 'improvement'],
  },
  { id: 'cf-effort', name: 'Engineering Days', kind: 'number', appliesTo: ['story', 'task', 'improvement', 'spike'] },
  { id: 'cf-needs-design', name: 'Needs Design Review', kind: 'boolean', appliesTo: ['story', 'epic', 'improvement'] },
  { id: 'cf-target-segment', name: 'Target Segment', kind: 'text', appliesTo: ['story', 'epic'] },
];

export const projects: Project[] = [
  {
    id: 'p-atlas',
    key: 'ATL',
    name: 'Atlas Workspace Revamp',
    description:
      'Rebuild the primary workspace shell with a faster navigation model, saved views and a unified task surface across web and tablet.',
    status: 'active',
    health: 'on_track',
    priority: 'critical',
    productOwnerId: 'u-1',
    teamIds: ['t-core', 't-design'],
    memberIds: ['u-1', 'u-2', 'u-4', 'u-5', 'u-11', 'u-14', 'u-7'],
    startDate: daysAgo(96),
    targetReleaseDate: daysFromToday(38),
    progress: 62,
    color: chartPalette[0]!,
    productArea: 'Core Experience',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-orbit',
    key: 'ORB',
    name: 'Orbit Analytics Suite',
    description:
      'Self-serve product analytics with cohort retention, funnel exploration and scheduled executive digests backed by the new metrics store.',
    status: 'active',
    health: 'at_risk',
    priority: 'high',
    productOwnerId: 'u-3',
    teamIds: ['t-growth', 't-platform'],
    memberIds: ['u-3', 'u-6', 'u-9', 'u-10', 'u-8', 'u-12'],
    startDate: daysAgo(64),
    targetReleaseDate: daysFromToday(21),
    progress: 44,
    color: chartPalette[1]!,
    productArea: 'Analytics',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-beacon',
    key: 'BCN',
    name: 'Beacon Onboarding',
    description:
      'Guided first-run experience with role-aware checklists, in-product tours and activation milestone tracking for new workspaces.',
    status: 'active',
    health: 'on_track',
    priority: 'high',
    productOwnerId: 'u-3',
    teamIds: ['t-growth', 't-design'],
    memberIds: ['u-3', 'u-5', 'u-11', 'u-14', 'u-9'],
    startDate: daysAgo(41),
    targetReleaseDate: daysFromToday(54),
    progress: 33,
    color: chartPalette[4]!,
    productArea: 'Growth',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-forge',
    key: 'FRG',
    name: 'Forge Platform Hardening',
    description:
      'Multi-region failover, tenant isolation guarantees and a rewritten permissions service to unblock enterprise procurement.',
    status: 'active',
    health: 'off_track',
    priority: 'critical',
    productOwnerId: 'u-8',
    teamIds: ['t-platform', 't-quality'],
    memberIds: ['u-8', 'u-6', 'u-10', 'u-7', 'u-12', 'u-2'],
    startDate: daysAgo(132),
    targetReleaseDate: daysFromToday(9),
    progress: 71,
    color: chartPalette[5]!,
    productArea: 'Platform',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-canvas',
    key: 'CNV',
    name: 'Canvas Design System v3',
    description:
      'Token-driven component library with dark mode parity, documented accessibility contracts and automated visual regression.',
    status: 'planning',
    health: 'on_track',
    priority: 'medium',
    productOwnerId: 'u-5',
    teamIds: ['t-design', 't-core'],
    memberIds: ['u-5', 'u-11', 'u-4', 'u-14'],
    startDate: daysFromToday(-8),
    targetReleaseDate: daysFromToday(96),
    progress: 11,
    color: chartPalette[2]!,
    productArea: 'Design',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-relay',
    key: 'RLY',
    name: 'Relay Integrations',
    description:
      'Outbound webhooks, a public REST surface and first-party connectors for calendar, chat and source control providers.',
    status: 'on_hold',
    health: 'at_risk',
    priority: 'medium',
    productOwnerId: 'u-1',
    teamIds: ['t-platform'],
    memberIds: ['u-1', 'u-6', 'u-10'],
    startDate: daysAgo(150),
    targetReleaseDate: daysFromToday(120),
    progress: 26,
    color: chartPalette[6]!,
    productArea: 'Platform',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
  {
    id: 'p-pulse',
    key: 'PLS',
    name: 'Pulse Mobile Companion',
    description:
      'Read-and-respond mobile companion for approvals, standup updates and notification triage. Shipped last quarter.',
    status: 'completed',
    health: 'on_track',
    priority: 'low',
    productOwnerId: 'u-3',
    teamIds: ['t-core'],
    memberIds: ['u-3', 'u-14', 'u-12'],
    startDate: daysAgo(240),
    targetReleaseDate: daysAgo(30),
    progress: 100,
    color: chartPalette[7]!,
    productArea: 'Mobile',
    workspaceId: DEFAULT_WORKSPACE_ID,
  },
];

export const risks: Risk[] = [
  {
    id: 'r-1',
    title: 'Permissions service migration has no rollback path',
    description:
      'The new permissions service writes directly to the tenant graph. A bad deploy cannot be reverted without a manual replay of the audit log.',
    severity: 'critical',
    status: 'mitigating',
    ownerId: 'u-6',
    projectId: 'p-forge',
    releaseId: 'rel-forge-2',
    identifiedOn: daysAgo(19),
    mitigation: 'Dual-write behind a feature flag for two sprints, then flip reads after a verified shadow comparison.',
  },
  {
    id: 'r-2',
    title: 'Metrics store query latency above SLA at p95',
    description: 'Cohort queries over 90-day windows exceed the 2s budget on the largest three tenants.',
    severity: 'high',
    status: 'open',
    ownerId: 'u-9',
    projectId: 'p-orbit',
    releaseId: 'rel-orbit-1',
    identifiedOn: daysAgo(11),
    mitigation: 'Pre-aggregate daily rollups and cap interactive windows at 30 days until the columnar store lands.',
  },
  {
    id: 'r-3',
    title: 'Single frontend owner for the new shell',
    description: 'Atlas shell work is concentrated on one engineer who is already over capacity.',
    severity: 'high',
    status: 'mitigating',
    ownerId: 'u-2',
    projectId: 'p-atlas',
    identifiedOn: daysAgo(26),
    mitigation: 'Pair rotation from the second sprint and move two navigation stories to the design-system track.',
  },
  {
    id: 'r-4',
    title: 'SOC 2 evidence collection is manual',
    description: 'Audit evidence for access reviews is assembled by hand each quarter and will not scale.',
    severity: 'medium',
    status: 'open',
    ownerId: 'u-8',
    projectId: 'p-forge',
    identifiedOn: daysAgo(44),
    mitigation: 'Scope an evidence export job in the Relay integrations backlog.',
  },
  {
    id: 'r-5',
    title: 'Onboarding copy not localised',
    description: 'Beacon checklists ship English-only, which blocks the EMEA launch plan.',
    severity: 'medium',
    status: 'accepted',
    ownerId: 'u-3',
    projectId: 'p-beacon',
    identifiedOn: daysAgo(7),
    mitigation: 'Accepted for v1; localisation tracked as a follow-up initiative next quarter.',
  },
  {
    id: 'r-6',
    title: 'Visual regression coverage gap in dark mode',
    description: 'Canvas v3 has no automated dark-mode snapshots, so contrast regressions ship unnoticed.',
    severity: 'low',
    status: 'resolved',
    ownerId: 'u-7',
    projectId: 'p-canvas',
    identifiedOn: daysAgo(31),
    mitigation: 'Dual-theme snapshot job added to CI and now gating merges.',
  },
];
